<template>
  <div class="dc-page catalog-v2"><div class="dc-container">
    <section class="dc-page-head"><div><span class="dc-eyebrow">ASSET CATALOG</span><h1 class="dc-title">资产目录</h1><p class="dc-subtitle">按业务主题、数仓层级和关键词浏览全部在用数据资产，不再截断 200 条。</p></div><div class="dc-toolbar"><el-input v-model="keyword" clearable placeholder="搜索数据集名称或表名" @keyup.enter="search"/><el-button type="primary" @click="search">查询</el-button></div></section>
    <div class="catalog-layout">
      <aside class="dc-card catalog-side"><div class="side-title">业务目录</div><button :class="{active:!selected}" @click="chooseCatalog('')"><span>全部资产</span><small>ALL</small></button><button v-for="c in catalogs" :key="c.code" :class="{active:selected===c.code}" @click="chooseCatalog(c.code)"><span>{{c.name}}</span><small>{{c.code}}</small></button></aside>
      <section class="dc-card asset-list"><div class="list-head"><div><b>{{total}} 个数据集</b><span v-if="selected"> · {{selected}}</span></div><span>第 {{startRow}}–{{endRow}} 条</span></div><div v-if="loading" class="dc-empty">正在加载资产目录…</div><RouterLink v-for="item in rows" :key="item.assetId" :to="`/datasets/${item.assetId}`" class="asset-row"><div class="asset-main"><div class="asset-title"><span class="layer-chip" :data-layer="item.layerCode">{{item.layerCode}}</span><b>{{item.bizName}}</b></div><code class="dc-tech">{{item.tableName}}</code><p>{{item.catalogCode}} · {{item.workspaceCode}} · {{item.status==='ONLINE'?'在用':item.status}}</p></div><div class="asset-meta"><span>{{item.techOwner||'未登记'}}</span><span>{{item.updateFreq||'—'}}</span><ArrowRight :size="17"/></div></RouterLink><div v-if="!loading && rows.length===0" class="dc-empty">没有符合条件的数据集。</div><footer v-if="total" class="pagination"><button :disabled="page===1" @click="go(page-1)">上一页</button><button v-for="p in visiblePages" :key="p" :class="{active:p===page}" @click="go(p)">{{p}}</button><button :disabled="page===totalPages" @click="go(page+1)">下一页</button></footer></section>
    </div>
  </div></div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { ArrowRight } from 'lucide-vue-next'
import { assetApi, type DatasetBrief } from '@/api/client'

const keyword=ref(''); const selected=ref(''); const catalogs=ref<any[]>([]); const rows=ref<DatasetBrief[]>([]); const total=ref(0); const page=ref(1); const pageSize=20; const loading=ref(false)
const totalPages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize)))
const startRow=computed(()=>total.value?(page.value-1)*pageSize+1:0)
const endRow=computed(()=>Math.min(page.value*pageSize,total.value))
const visiblePages=computed(()=>{const result:number[]=[];const start=Math.max(1,Math.min(page.value-2,totalPages.value-4));for(let p=start;p<=Math.min(totalPages.value,start+4);p+=1)result.push(p);return result})
async function load(){loading.value=true;try{const data=await assetApi.tablePage({offset:(page.value-1)*pageSize,limit:pageSize,keyword:keyword.value.trim()||undefined,catalog:selected.value||undefined,status:'ONLINE'});rows.value=data.items;total.value=data.total;if(page.value>totalPages.value){page.value=totalPages.value;await load()}}finally{loading.value=false}}
function search(){page.value=1;load()}
function chooseCatalog(code:string){selected.value=code;page.value=1;load()}
function go(value:number){page.value=Math.min(Math.max(1,value),totalPages.value);load();window.scrollTo({top:0,behavior:'smooth'})}
onMounted(async()=>{try{catalogs.value=await assetApi.catalogs() as any[]}catch{};await load()})
</script>

<style scoped>
.catalog-v2{background:#eef6fa;min-height:100%}.dc-toolbar :deep(.el-input){width:280px}.catalog-layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:14px;align-items:start}.catalog-side{padding:12px;position:sticky;top:78px;display:grid;gap:3px}.side-title{font-size:10px;color:#6e8795;font-weight:800;padding:6px 8px}.catalog-side button{border:0;background:transparent;border-radius:8px;padding:9px;text-align:left;color:#557486;cursor:pointer;display:grid;gap:2px}.catalog-side button small{font-size:8px;color:#8298a4}.catalog-side button.active,.catalog-side button:hover{background:#e1f1f7;color:#126f95}.asset-list{padding:0 18px 12px;min-width:0}.list-head{height:50px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e3ebef}.list-head b{font-size:12px}.list-head span{font-size:10px;color:#758d99}.asset-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;padding:15px 2px;border-bottom:1px solid #edf2f5;align-items:center}.asset-row:hover{background:#f8fbfd}.asset-main{min-width:0}.asset-title{display:flex;align-items:center;gap:8px}.asset-title b{font-size:13px;color:#264f64}.asset-main code{display:block;font-size:10px;margin-top:6px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.asset-main p{font-size:9px;color:#718995;margin:6px 0 0}.asset-meta{display:flex;align-items:center;gap:12px;color:#718a98;font-size:9px}.layer-chip{padding:3px 6px;border-radius:5px;background:#edf3f6;color:#486575;font-size:8px;font-weight:800}.layer-chip[data-layer="ODS"]{background:#eeeafd;color:#4f3fa8}.layer-chip[data-layer="DWD"]{background:#e2f4f1;color:#0d6f68}.layer-chip[data-layer="DWS"]{background:#e3f1f8;color:#126b93}.layer-chip[data-layer="ADS"]{background:#fff3da;color:#83570a}.layer-chip[data-layer="DIM"]{background:#edf1f4;color:#44596a}.pagination{display:flex;justify-content:flex-end;gap:5px;padding:12px 0 2px}.pagination button{min-width:30px;height:28px;border:1px solid #d1e0e7;border-radius:6px;background:#fff;color:#527184;font-size:9px;cursor:pointer}.pagination button.active{border-color:#2c8db4;background:#edf8fc;color:#16749a}.pagination button:disabled{opacity:.4}@media(max-width:980px){.catalog-layout{grid-template-columns:1fr}.catalog-side{position:static;display:flex;overflow:auto}.catalog-side .side-title{display:none}.catalog-side button{flex:0 0 auto;min-width:120px}}@media(max-width:700px){.dc-toolbar :deep(.el-input){width:100%}.asset-row{grid-template-columns:1fr}.asset-meta{justify-content:space-between}.list-head{align-items:flex-start;flex-direction:column;height:auto;padding:12px 0;gap:4px}}
</style>
